/** Tous les textes de l'interface : un seul endroit à relire, et à traduire un jour. */
export const fr = {
  app: 'Text to One',
  untitled: 'Document sans titre',

  home: {
    tagline: 'La suite bureautique libre. Le tableur et les présentations arrivent bientôt.',
    text: 'Texte',
    textHint: 'Écrire un document',
    sheet: 'Tableur',
    sheetHint: 'Calculer et organiser des données',
    slides: 'Présentations',
    slidesHint: 'Créer des diaporamas',
    soon: 'Bientôt',
    open: 'Ouvrir un document…',
    recent: 'Documents récents',
    noRecent: 'Aucun document récent pour le moment.',
  },

  editor: { label: 'Contenu du document', toolbar: 'Mise en forme' },

  toolbar: {
    undo: 'Annuler (Ctrl+Z)',
    redo: 'Rétablir (Ctrl+Y)',
    style: 'Style de paragraphe',
    paragraph: 'Paragraphe',
    heading: (niveau: number) => `Titre ${niveau}`,
    font: 'Police',
    fontDefault: 'Police par défaut',
    size: 'Taille du texte',
    lineHeight: 'Interligne',
    lineHeightDefault: 'Interligne',
    bold: 'Gras (Ctrl+B)',
    italic: 'Italique (Ctrl+I)',
    underline: 'Souligné (Ctrl+U)',
    strike: 'Barré',
    superscript: 'Exposant',
    subscript: 'Indice',
    textColor: 'Couleur du texte',
    highlight: 'Surlignage',
    clearFormat: 'Effacer la mise en forme',
    alignLeft: 'Aligner à gauche',
    alignCenter: 'Centrer',
    alignRight: 'Aligner à droite',
    alignJustify: 'Justifier',
    bulletList: 'Liste à puces',
    orderedList: 'Liste numérotée',
    taskList: 'Liste de tâches',
    quote: 'Citation',
    link: 'Lien (Ctrl+K)',
    image: 'Insérer une image',
    table: 'Tableau',
    hr: 'Ligne de séparation',
    pageBreak: 'Saut de page',
    noColor: 'Aucune couleur',
    otherColor: 'Autre couleur…',
  },

  table: {
    insert: 'Insérer un tableau 3 × 3',
    rowBefore: 'Ajouter une ligne au-dessus',
    rowAfter: 'Ajouter une ligne en dessous',
    deleteRow: 'Supprimer la ligne',
    colBefore: 'Ajouter une colonne à gauche',
    colAfter: 'Ajouter une colonne à droite',
    deleteCol: 'Supprimer la colonne',
    merge: 'Fusionner les cellules',
    split: 'Scinder la cellule',
    header: "Ligne d'en-tête",
    deleteTable: 'Supprimer le tableau',
  },

  status: {
    words: (n: number) => `${n} mot${n > 1 ? 's' : ''}`,
    chars: (n: number) => `${n} caractère${n > 1 ? 's' : ''}`,
    zoomIn: 'Agrandir',
    zoomOut: 'Réduire',
    zoomReset: 'Revenir à 100 %',
  },

  find: {
    label: 'Rechercher',
    replaceWith: 'Remplacer par',
    matchCase: 'Respecter la casse',
    previous: 'Occurrence précédente',
    next: 'Occurrence suivante',
    replaceOne: 'Remplacer',
    replaceAll: 'Tout remplacer',
    close: 'Fermer la recherche',
    none: 'Aucun résultat',
    count: (position: number, total: number) => `${position} sur ${total}`,
  },

  dialog: {
    linkTitle: 'Insérer un lien',
    linkLabel: 'Adresse du lien (laisser vide pour retirer le lien)',
    linkInvalid: "Cette adresse n'est pas autorisée. Utilise http, https, mailto ou tel.",
    ok: 'OK',
    cancel: 'Annuler',
  },

  notice: {
    exported: (nom: string) => `Exporté : ${nom}`,
    imageTooBig: "Cette image dépasse 15 Mo : elle n'a pas été insérée.",
  },

  errors: {
    openUnknown: "Impossible d'ouvrir ce fichier.",
    save: (détail: string) => `Impossible d'enregistrer : ${détail}`,
    export: (détail: string) => `Impossible d'exporter : ${détail}`,
    unknown: 'Erreur inconnue.',
    unsupported: (nom: string) => `Ce type de fichier n'est pas pris en charge${nom ? ` : « ${nom} »` : ''}.`,
  },

  sheet: {
    grid: 'Feuille de calcul',
    toolbar: {
      label: 'Outils du tableur',
      undo: 'Annuler (Ctrl+Z)',
      redo: 'Rétablir (Ctrl+Y)',
      bold: 'Gras (Ctrl+B)',
      italic: 'Italique (Ctrl+I)',
      alignLeft: 'Aligner à gauche',
      alignCenter: 'Centrer',
      alignRight: 'Aligner à droite',
      textColor: 'Couleur du texte',
      fillColor: 'Couleur de fond',
      format: 'Format des nombres',
      formatGeneral: 'Standard',
      formatInt: 'Nombre entier',
      formatDec2: 'Deux décimales',
      formatPercent: 'Pourcentage',
      formatEur: 'Euro',
      insertRow: 'Insérer une ligne au-dessus',
      insertCol: 'Insérer une colonne à gauche',
      deleteRow: 'Supprimer la ligne',
      deleteCol: 'Supprimer la colonne',
      clear: 'Effacer le contenu',
      fillDown: 'Recopier vers le bas (Ctrl+D)',
      noColor: 'Aucune couleur',
      otherColor: 'Autre couleur…',
    },
    nameBox: 'Cellule sélectionnée',
    formulaInput: 'Contenu de la cellule : un nombre, du texte, ou une formule qui commence par =',
    ready: 'Prêt',
    stats: (nombre: number, somme: string, moyenne: string) => `Nombre : ${nombre} · Somme : ${somme} · Moyenne : ${moyenne}`,
  },
};
