/** Tous les textes de l'interface : un seul endroit à relire, et à traduire un jour. */
export const fr = {
  app: 'Text to One',
  untitled: 'Document sans titre',

  home: {
    tagline: 'La suite bureautique libre : texte, tableur et présentations.',
    text: 'Texte',
    textHint: 'Écrire un document',
    sheet: 'Tableur',
    sheetHint: 'Calculer et organiser des données',
    slides: 'Présentations',
    slidesHint: 'Créer des diaporamas',
    soon: 'Bientôt',
    open: 'Ouvrir un document…',
    recent: 'Documents récents',
    noRecent: 'Aucun document récent pour le moment.',
  },

  editor: {
    label: 'Contenu du document',
    toolbar: 'Mise en forme',
    tocTitle: 'Sommaire',
    noHeadings: 'Aucun titre dans le document : mets des titres (Titre 1, 2 ou 3) pour obtenir un sommaire.',
    focusExit: 'Quitter le mode concentration',
  },

  themes: {
    title: 'Thèmes',
    intro: 'Choisissez l’apparence de Text to One. La feuille de papier reste blanche : ce que vous voyez est ce qui sera imprimé.',
    list: 'Thèmes disponibles',
    system: 'Automatique',
    systemHint: 'Suit le système',
    light: 'Clair',
    dark: 'Sombre',
    custom: 'Personnalisé',
    customTitle: 'Votre thème',
    customIntro: 'Quatre couleurs suffisent : le reste s’en déduit.',
    background: 'Fond',
    surface: 'Barres et menus',
    text: 'Texte',
    accent: 'Accent',
    reset: 'Remettre les couleurs de départ',
    close: 'Fermer',
    good: 'Ces couleurs se lisent bien.',
    lowText: 'Le texte est difficile à lire sur ces couleurs.',
    lowAccent: 'Les boutons colorés sont difficiles à lire.',
    lowMuted: 'Les textes discrets sont difficiles à lire.',
    open: 'Thèmes…',
  },

  toolbar: {
    undo: 'Annuler (Ctrl+Z)',
    redo: 'Rétablir (Ctrl+Y)',
    print: 'Imprimer (Ctrl+P)',
    style: 'Style de paragraphe',
    paragraph: 'Paragraphe',
    heading: (niveau: number) => `Titre ${niveau}`,
    font: 'Police',
    fontDefault: 'Police par défaut',
    size: 'Taille du texte',
    lineHeight: 'Interligne',
    lineHeightDefault: 'Interligne',
    bold: 'Gras (Ctrl+B)',
    italic: 'Italique (Ctrl+I)',
    underline: 'Souligné (Ctrl+U)',
    strike: 'Barré',
    superscript: 'Exposant',
    subscript: 'Indice',
    textColor: 'Couleur du texte',
    highlight: 'Surlignage',
    clearFormat: 'Effacer la mise en forme',
    alignLeft: 'Aligner à gauche',
    alignCenter: 'Centrer',
    alignRight: 'Aligner à droite',
    alignJustify: 'Justifier',
    bulletList: 'Liste à puces',
    orderedList: 'Liste numérotée',
    taskList: 'Liste de tâches',
    quote: 'Citation',
    link: 'Lien (Ctrl+K)',
    image: 'Insérer une image',
    table: 'Tableau',
    hr: 'Ligne de séparation',
    pageBreak: 'Saut de page',
    math: 'Formule mathématique (Ctrl+Alt+M)',
    media: 'Insérer un son ou une vidéo',
    date: 'Insérer la date du jour (Ctrl+Maj+D)',
    toc: 'Insérer un sommaire',
    noColor: 'Aucune couleur',
    otherColor: 'Autre couleur…',
  },

  table: {
    insert: 'Insérer un tableau 3 × 3',
    rowBefore: 'Ajouter une ligne au-dessus',
    rowAfter: 'Ajouter une ligne en dessous',
    deleteRow: 'Supprimer la ligne',
    colBefore: 'Ajouter une colonne à gauche',
    colAfter: 'Ajouter une colonne à droite',
    deleteCol: 'Supprimer la colonne',
    merge: 'Fusionner les cellules',
    split: 'Scinder la cellule',
    header: "Ligne d'en-tête",
    deleteTable: 'Supprimer le tableau',
  },

  status: {
    words: (n: number) => `${n} mot${n > 1 ? 's' : ''}`,
    chars: (n: number) => `${n} caractère${n > 1 ? 's' : ''}`,
    zoomIn: 'Agrandir',
    zoomOut: 'Réduire',
    zoomReset: 'Revenir à 100 %',
  },

  find: {
    label: 'Rechercher',
    replaceWith: 'Remplacer par',
    matchCase: 'Respecter la casse',
    previous: 'Occurrence précédente',
    next: 'Occurrence suivante',
    replaceOne: 'Remplacer',
    replaceAll: 'Tout remplacer',
    close: 'Fermer la recherche',
    none: 'Aucun résultat',
    count: (position: number, total: number) => `${position} sur ${total}`,
  },

  dialog: {
    linkTitle: 'Insérer un lien',
    linkLabel: 'Adresse du lien (laisser vide pour retirer le lien)',
    linkInvalid: "Cette adresse n'est pas autorisée. Utilise http, https, mailto ou tel.",
    ok: 'OK',
    cancel: 'Annuler',
  },

  math: {
    title: 'Insérer une formule',
    editTitle: 'Modifier la formule',
    intro: 'Écris la formule en LaTeX, par exemple \\frac{a}{b} ou x^2. Dans le texte, tu peux aussi taper $x^2$ directement.',
    label: 'Formule (LaTeX)',
    snippets: 'Raccourcis',
    mode: 'Emplacement',
    inline: 'Dans le texte',
    block: 'Sur sa propre ligne',
    empty: 'L’aperçu apparaît ici.',
  },

  media: {
    title: 'Audio ou vidéo',
    tooBig: "Ce fichier dépasse 25 Mo : il n'a pas été inséré.",
    unsupported: "Ce type de fichier n'est pas pris en charge. Formats acceptés : mp3, m4a, aac, ogg, wav, flac, mp4, webm.",
    untitled: 'Sans titre',
    play: 'Lire',
    pause: 'Mettre en pause',
    placeholder: (genre: 'audio' | 'video', titre: string) => `[${genre === 'video' ? 'vidéo' : 'audio'} : ${titre}]`,
  },

  notice: {
    exported: (nom: string) => `Exporté : ${nom}`,
    imageTooBig: "Cette image dépasse 15 Mo : elle n'a pas été insérée.",
  },

  errors: {
    openUnknown: "Impossible d'ouvrir ce fichier.",
    save: (détail: string) => `Impossible d'enregistrer : ${détail}`,
    export: (détail: string) => `Impossible d'exporter : ${détail}`,
    unknown: 'Erreur inconnue.',
    unsupported: (nom: string) => `Ce type de fichier n'est pas pris en charge${nom ? ` : « ${nom} »` : ''}.`,
  },

  sheet: {
    grid: 'Feuille de calcul',
    toolbar: {
      label: 'Outils du tableur',
      undo: 'Annuler (Ctrl+Z)',
      redo: 'Rétablir (Ctrl+Y)',
      bold: 'Gras (Ctrl+B)',
      italic: 'Italique (Ctrl+I)',
      alignLeft: 'Aligner à gauche',
      alignCenter: 'Centrer',
      alignRight: 'Aligner à droite',
      textColor: 'Couleur du texte',
      fillColor: 'Couleur de fond',
      format: 'Format des nombres',
      formatGeneral: 'Standard',
      formatInt: 'Nombre entier',
      formatDec2: 'Deux décimales',
      formatPercent: 'Pourcentage',
      formatEur: 'Euro',
      media: 'Son ou vidéo de la cellule',
      insertRow: 'Insérer une ligne au-dessus',
      insertCol: 'Insérer une colonne à gauche',
      deleteRow: 'Supprimer la ligne',
      deleteCol: 'Supprimer la colonne',
      clear: 'Effacer le contenu',
      fillDown: 'Recopier vers le bas (Ctrl+D)',
      noColor: 'Aucune couleur',
      otherColor: 'Autre couleur…',
    },
    media: {
      player: 'Lecteur de la cellule',
      replace: 'Remplacer…',
      remove: 'Retirer',
      close: 'Fermer',
      tooMany: (max: number) => `Un classeur ne peut pas contenir plus de ${max} sons ou vidéos.`,
      notExported: "Les sons et vidéos ne sont pas inclus dans ce format : ils restent dans le fichier .tts.",
    },
    nameBox: 'Cellule sélectionnée',
    formulaInput: 'Contenu de la cellule : un nombre, du texte, ou une formule qui commence par =',
    ready: 'Prêt',
    stats: (nombre: number, somme: string, moyenne: string) => `Nombre : ${nombre} · Somme : ${somme} · Moyenne : ${moyenne}`,
  },

  slides: {
    label: 'Outils des présentations',
    panel: 'Diapositives',
    stage: 'Diapositive en cours de modification',
    thumb: (n: number) => `Diapositive ${n}`,
    toolbar: {
      undo: 'Annuler (Ctrl+Z)',
      redo: 'Rétablir (Ctrl+Y)',
      newSlide: 'Nouvelle diapositive',
      layout: 'Mise en page de la nouvelle diapositive',
      layoutTitle: 'Titre',
      layoutContent: 'Titre et contenu',
      layoutBlank: 'Vide',
      duplicateSlide: 'Dupliquer la diapositive',
      deleteSlide: 'Supprimer la diapositive',
      moveUp: 'Monter la diapositive',
      moveDown: 'Descendre la diapositive',
      insertText: 'Zone de texte',
      insertRect: 'Rectangle',
      insertEllipse: 'Ellipse',
      insertImage: 'Insérer une image',
      insertMedia: 'Insérer un son ou une vidéo',
      size: 'Taille du texte',
      bold: 'Gras (Ctrl+B)',
      italic: 'Italique (Ctrl+I)',
      underline: 'Souligné',
      alignLeft: 'Aligner à gauche',
      alignCenter: 'Centrer',
      alignRight: 'Aligner à droite',
      textColor: 'Couleur du texte',
      fillColor: 'Couleur de remplissage',
      strokeColor: 'Couleur du contour',
      background: 'Fond de la diapositive',
      bringFront: 'Premier plan',
      sendBack: 'Arrière-plan',
      duplicateObject: 'Dupliquer l’objet (Ctrl+D)',
      deleteObject: 'Supprimer l’objet',
      present: 'Présenter (F5)',
      noColor: 'Aucune couleur',
      otherColor: 'Autre couleur…',
    },
    present: {
      label: 'Présentation en plein écran',
      hint: 'Flèches ou clic pour avancer · Échap pour quitter',
      position: (n: number, total: number) => `${n} / ${total}`,
    },
    status: (n: number, total: number, objets: number) => `Diapositive ${n} sur ${total} · ${objets} objet${objets > 1 ? 's' : ''}`,
  },
};
